### ISSUE TITLE
Cannot deploy. Keep getting 'Your site is using the `relative_permalinks` configuration option. '

### ISSUE THREAD

**Issue by EricZhang90** [codinfox/lanyon-codinfox.github.io#8]
I forked the dev branch. And keep getting error email saying that "Your site is using the `relative_permalinks` configuration option. ..."
The config file is the only file I have  changed. I don't find `relative_permalinks` in the config file. Is it in somewhere else?

_config.yml
```
# Site Info
title: Github Page
tagline: "Eric' GitHub Page"
#description: ''
#baseurl: ""
url: https://Ericzhang90.github.io
logo: 'https://avatars1.githubusercontent.com/u/11701625?v=3&amp;s=400'

# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: /:year-:month-:day-:title/
future: true

version: 1.0.0

# About/contact
author:
  name: Eric
  description: Eric's GitHub page.
  contact:
    github:    https://github.com/ericzhang90
    email:     lzhang.eric@gmail.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Blog:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'
  Github Project: 
    - 'https://github.com/ericzhang90/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: /public/img/we_will_be_giants_by_yalestewart.jpg
  caption: Original Artwork &copy; <a href="http://yalestewart.deviantart.com/art/We-Will-Be-Giants-370176475">Yale Stewart</a>

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-00000000-1' # leave blank if you don't want google analytics
disqus_short_name: 'your_short_name' # leave blank if you don't want disqus


```
